name: 'Database Lab: realistic DB testing in CI'
branding:
  icon: 'database'  
  color: 'orange'
description: 'Test DB migrations using DB branches provided by Database Lab Engine (DLE)'
inputs:
  commands:
    description: 'List of commands to run DB migrations'
    required: true
  dbname:
    description: 'The database that the workflow is running with'
    required: false
    default: ""
  migration_envs:
    description: 'List of environment variables that will be set during migrations running'
    required: false
  download_artifacts:
    description: 'Option to download artifacts'
    required: false
    default: "false"

  observation_interval:
    description: 'Observation interval'
    required: false
    default: "10"
  max_lock_duration:
    description: 'Max lock duration'
    required: false
    default: "10"
  max_duration:
    description: 'Max duration'
    required: false
    default: "3600"

outputs:
  response:
    value: Done
    description: 'The result of migration checks'

runs:
  using: 'composite'
  steps:
    - name: DB migration with DLE
      uses: postgres-ai/dle-github-actions/core@master
      with:
        commands: ${{ inputs.commands }}
        dbname: ${{ inputs.dbname }}
        migration_envs: ${{ inputs.migration_envs }}
        download_artifacts: ${{ inputs.download_artifacts }}
        observation_interval: ${{ inputs.observation_interval }}
        max_lock_duration: ${{ inputs.max_lock_duration }}
        max_duration: ${{ inputs.max_duration }}

    - name: Post comment to PR
      if: ${{ always() && github.event_name == 'pull_request' }}
      uses: peter-evans/create-or-update-comment@v2.1.0
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-file: 'artifacts/report.md'
